// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sparcc_matrix_cpp
arma::mat sparcc_matrix_cpp(const arma::mat& data, int iter, int inner_iter, double th, int nthreads);
RcppExport SEXP _ggNetView_sparcc_matrix_cpp(SEXP dataSEXP, SEXP iterSEXP, SEXP inner_iterSEXP, SEXP thSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< int >::type inner_iter(inner_iterSEXP);
    Rcpp::traits::input_parameter< double >::type th(thSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sparcc_matrix_cpp(data, iter, inner_iter, th, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// spieceasi_norm_cpp
arma::mat spieceasi_norm_cpp(const arma::mat& data, double tol);
RcppExport SEXP _ggNetView_spieceasi_norm_cpp(SEXP dataSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(spieceasi_norm_cpp(data, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ggNetView_sparcc_matrix_cpp", (DL_FUNC) &_ggNetView_sparcc_matrix_cpp, 5},
    {"_ggNetView_spieceasi_norm_cpp", (DL_FUNC) &_ggNetView_spieceasi_norm_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ggNetView(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
