ggNetView_multi <- function(mat,
                            group,
                            layout = NULL,
                            node_add = 7,
                            ring_n = NULL,
                            r = 1,
                            center = TRUE,
                            idx = NULL,
                            shrink = 1,
                            k_nn = 8,
                            push_others_delta = 0,
                            layout.module = c("random", "adjacent", "order"),
                            shape = 21,
                            pointalpha = 1,
                            pointsize = c(1,10),
                            pointstroke = 0.3,
                            group.by = "Modularity",
                            jitter = FALSE,
                            jitter_sd = 0.1,
                            mapping_line = FALSE,
                            linealpha = 0.25,
                            linecolor = "grey70",
                            label = FALSE,
                            labelsize = 10,
                            labelsegmentsize = 1,
                            labelsegmentalpha = 1,
                            add_outer = FALSE,
                            outerwidth = 1.25,
                            outerlinetype = 2,
                            outeralpha = 0.5,
                            nodelabsize = 5,
                            remove = FALSE,
                            orientation = "up",
                            angle = 0,
                            scale = T,
                            anchor_dist = 6,
                            seed = 1115){

}
