# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparcc_matrix_cpp <- function(data, iter, inner_iter, th, nthreads = 0L) {
    .Call(`_ggNetView_sparcc_matrix_cpp`, data, iter, inner_iter, th, nthreads)
}

spieceasi_norm_cpp <- function(data, tol = 1e-15) {
    .Call(`_ggNetView_spieceasi_norm_cpp`, data, tol)
}

